### PR TITLE
Fix: Prevent saving empty todos during edit

### PR DESCRIPTION
**Pull request by DevastatorDev**
Resolved an issue where the application would allow saving an empty todo when editing an existing item. Now, the todo will not be updated if the edited content is left empty, ensuring that empty tasks are not saved to the list.

### CODE REVIEW

**Comment by Master-utsav** [comment]
Screenshot 2024-08-21 205932
not only this, make sure todo will come in its previous state ( if user leave it empty)

**Comment by DevastatorDev** [comment]
Task : make sure todo will come in its previous state ( if user leave it empty)
Status : Completed
Feedback : Now check for any error if there is let me know

**Comment by Master-utsav** [comment]
Try to implement a feature of move up and down a particular todo (prioritize todo)

**Comment by DevastatorDev** [comment]
Ok

**Pull request merged**
